-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(32) NOT NULL,
    password character varying(16) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.users
    IS 'Tüm Kullanýcýlar Temel Sýnýf';

CREATE TABLE public.candidates
(
    user_id integer NOT NULL,
    first_name character varying(32) NOT NULL,
    last_name character varying(32) NOT NULL,
    identity_number character(11) NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (user_id)
);

COMMENT ON TABLE public.candidates
    IS 'Ýþ Arayanlar';

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(32) NOT NULL,
    web_address character varying(64) NOT NULL,
    phone_number character varying(32) NOT NULL,
    PRIMARY KEY (user_id)
);

COMMENT ON TABLE public.employers
    IS 'Ýþ verenler';

CREATE TABLE public.employees
(
    user_id integer NOT NULL,
    first_name character varying(32) NOT NULL,
    "last-name" character varying(32) NOT NULL,
    PRIMARY KEY (user_id)
);

COMMENT ON TABLE public.employees
    IS 'Sistem Çalýþanlarý';

CREATE TABLE public.employee_confirms
(
    id integer NOT NULL,
    employee_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.employee_confirms
    IS 'Sistem Çalýþanlarýnýn Tüm Onaylarý';

CREATE TABLE public.employee_confirm_employers
(
    employee_confirm_id integer NOT NULL,
    employers_id integer NOT NULL,
    PRIMARY KEY (employee_confirm_id)
);

COMMENT ON TABLE public.employee_confirm_employers
    IS 'Ýþ verenlerin Sistem Çalýþanlarý Tarafýndan Onaylanmasý';

CREATE TABLE public.verification_code_employers
(
    verification_code_id integer NOT NULL,
    employer_id integer NOT NULL,
    PRIMARY KEY (verification_code_id)
);

COMMENT ON TABLE public.verification_code_employers
    IS 'Ýþ verenlerin Doðrulama Kodlarý ';

CREATE TABLE public.verification_code_candidates
(
    verification_code_id integer NOT NULL,
    candidate_id integer NOT NULL,
    PRIMARY KEY (verification_code_id)
);

COMMENT ON TABLE public.verification_code_candidates
    IS 'Ýþ Arayanlarýn Doðrulama Kodlarý';

CREATE TABLE public.verification_codes
(
    id integer NOT NULL,
    code character(6) NOT NULL,
    is_verified boolean NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.verification_codes
    IS 'Doðrulama Kodlarý Temel Sýnýf';

CREATE TABLE public.job_titles
(
    id integer NOT NULL,
    title character varying(64) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.job_titles
    IS 'Ýþ Baþlýklarý Temel Sýnýf';

ALTER TABLE public.candidates
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employee_confirms
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (user_id)
    NOT VALID;


ALTER TABLE public.employee_confirm_employers
    ADD FOREIGN KEY (employee_confirm_id)
    REFERENCES public.employee_confirms (id)
    NOT VALID;


ALTER TABLE public.employee_confirm_employers
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.verification_code_candidates
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (user_id)
    NOT VALID;


ALTER TABLE public.verification_code_employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.verification_code_candidates
    ADD FOREIGN KEY (verification_code_id)
    REFERENCES public.verification_codes (id)
    NOT VALID;


ALTER TABLE public.verification_code_employers
    ADD FOREIGN KEY (verification_code_id)
    REFERENCES public.verification_codes (id)
    NOT VALID;

END;